rebugit:
  tracer:
    podCommonAnnotations:
      linkerd.io/inject: enabled
  dashboard:
    podCommonAnnotations:
      linkerd.io/inject: enabled
  postgresql:
    postgresqlPassword:
    primary:
      podAnnotations:
        linkerd.io/inject: enabled
  keycloak:
    auth:
      userName:
    podAnnotations:
      linkerd.io/inject: enabled
      config.linkerd.io/skip-inbound-ports: "7800" # skip keycloak cluster discovery
      config.linkerd.io/skip-outbound-ports: "7800"

ingress-nginx:
  controller:
    service:
      targetPorts:
        http: http
        https: http
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:XX-XXXX-X:XXXXXXXXX:certificate/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'