apiVersion: v1
kind: ConfigMap
metadata:
  name: rebugit-global-configmap
  namespace: {{.Release.Namespace}}
data:
  environment: "prod"

  database_host: "rebugit-postgresql.rebugit.svc.cluster.local"
  database_port: "5432"
  database_name: "rebugit"
  database_user_name: "app"
  database_admin_name: "postgres"

