apiVersion: v1
kind: Secret
metadata:
  name: rebugit-global-secrets
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  database_user_password: {{ default "default" .Values.postgresql.postgresqlUserPassword | b64enc }}
  database_admin_password: {{ default "default" .Values.postgresql.postgresqlPassword | b64enc }}
