kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "database.network.policy.name" . }}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{ include "database.network.policy.name" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: rebugit
  ingress:
    - ports:
        - port: 5432
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              app: {{ include "tracer.deployment.name" . }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: keycloak
