apiVersion: v1
kind: ConfigMap
metadata:
  name: rebugit-global-configmap
data:
  environment: "prod"

  database_host: "rebugit-postgresql"
  database_port: "5432"
  database_name: "rebugit"
  database_username: "app"
  database_admin: "postgres"

  authentication_internal_url: "http://rebugit-keycloak:8080/rebugit/keycloak"
  authentication_url: "http://localhost/rebugit/keycloak"

  dasboard_container_port: "8080"

  authentication_mode: "keycloak"

  tracer_api_url: "http://localhost/rebugit/api"

