apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-job
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.postgresql.migration.containers.name }}
          image: {{ .Values.postgresql.migration.containers.image.repository }}:{{ .Values.postgresql.migration.containers.image.tag }}
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 4
