apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-job
spec:
  template:
    spec:
      containers:
        - name: database-migration-job
          image: "{{.Values.rebugit.registry}}/{{.Values.rebugit.repository}}/migrator:{{.Values.database.migration.version}}"
          imagePullPolicy: Always
          env:
            - name: POSTGRES_ADMIN
              value: postgres
            - name: POSTGRES_PASSWORD
              value: {{.Values.database.admin.password}}
            - name: POSTGRES_HOST
              value: rebugit-postgresql
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER_PASSWORD
              value: {{.Values.database.user.password}}
      restartPolicy: Never
{{/*      ttlSecondsAfterFinished: 100*/}}
  backoffLimit: 3
