apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-job
  namespace: {{.Release.Namespace}}
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-keycloak
          image: stefanevinance/wait-for-200
          env:
            - name: URL
              value: "{{ include "isTLSEnabled" .}}://{{ include "authentication.service.name" .}}:8080/rebugit/keycloak/auth/"
      containers:
        - name: database-migration-job
          image: "{{.Values.postgresql.postgresqlMigration.registry}}/{{.Values.postgresql.postgresqlMigration.repository}}:{{.Values.postgresql.postgresqlMigration.version}}"
          imagePullPolicy: {{.Values.postgresql.postgresqlMigration.pullPolicy}}
          env:
            - name: POSTGRES_ADMIN
              valueFrom:
                configMapKeyRef:
                  key: database_admin_name
                  name: rebugit-global-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database_admin_password
                  name: rebugit-global-secrets
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: database_host
                  name: rebugit-global-configmap
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: database_port
                  name: rebugit-global-configmap
            - name: POSTGRES_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database_user_password
                  name: rebugit-global-secrets
            - name: KEYCLOAK_ADMIN_USER
              value: {{.Values.keycloak.auth.adminUser}}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{.Values.keycloak.auth.adminPassword}}
            - name: KEYCLOAK_REALM_NAME
              value: {{ include "authentication.keycloak.realm.name" .}}
            - name: KEYCLOAK_HOST
              valueFrom:
                configMapKeyRef:
                  key: authentication_internal_url
                  name: rebugit-global-configmap
            - name: KEYCLOAK_USER_NAME
              valueFrom:
                secretKeyRef:
                  key: keycloak_user_name
                  name: rebugit-global-secrets
            - name: KEYCLOAK_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keycloak_user_password
                  name: rebugit-global-secrets
            - name: REBUGIT_HOST
              value: "{{ include "isTLSEnabled" .}}://{{.Values.rebugit.host}}"
      restartPolicy: Never
{{/*      ttlSecondsAfterFinished: 100*/}}
  backoffLimit: 3
