apiVersion: v1
kind: Secret
metadata:
  name: rebugit-global-secrets
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  database_user_password: {{ .Values.postgresql.postgresqlUserPassword | b64enc }}
  database_admin_password: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  keycloak_user_password: {{.Values.keycloak.auth.userPassword | b64enc }}
  keycloak_user_name: {{.Values.keycloak.auth.userName | b64enc }}
