apiVersion: v1
kind: Secret
metadata:
  name: rebugit-global-secrets
type: Opaque
data:
  database_user_password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  database_admin_password: {{ .Values.postgresql.postgresqlUserPassword | b64enc | quote }}
