apiVersion: v1
kind: ConfigMap
metadata:
  name: rebugit-global-configmap
  namespace: {{.Release.Namespace}}
data:
  environment: "prod"

  database_host: "rebugit-postgresql.rebugit.svc.cluster.local"
  database_port: "5432"
  database_name: "rebugit"
  database_user_name: "app"
  database_admin_name: "postgres"

  authentication_internal_url: "{{ include "isTLSEnabled" .}}://{{ include "authentication.service.name" .}}:8080/rebugit/keycloak"
  authentication_url: "{{ include "isTLSEnabled" .}}://{{.Values.rebugit.host}}/rebugit/keycloak"

  dasboard_container_port: "8080"

  authentication_mode: "keycloak"

  tracer_api_url: "{{ include "isTLSEnabled" .}}://{{.Values.rebugit.host}}/rebugit/api"

