apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rebugit-tracer-ingress
  namespace: {{.Release.Namespace}}
  annotations:
    {{- range $k, $v := .Values.tracer.ingress.annotations }}
    {{ $k }}: {{ $v -}}
    {{ end }}
spec:
  rules:
    - http:
        paths:
          - path: /rebugit/api/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "tracer.service.name" . }}
                port:
                  number: {{.Values.tracer.port}}