apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tracer.deployment.name" . }}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{ include "tracer.deployment.name" . }}
  annotations: {{ include "default.annotations" . | nindent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "tracer.deployment.name" . }}
  template:
    metadata:
      namespace: {{.Release.Namespace}}
      annotations:
      {{- range $k, $v := .Values.tracer.podCommonAnnotations }}
        {{ $k }}: {{ $v -}}
      {{ end }}
      labels:
        app: {{ include "tracer.deployment.name" . }}
    spec:
      initContainers:
        - name: wait-for-keycloak
          image: stefanevinance/wait-for-200
          env:
            - name: URL
              value: "{{ include "isTLSEnabled" .}}://{{ include "authentication.service.name" .}}:8080/rebugit/keycloak/auth/"
      containers:
        - name: tracer
          image: "{{.Values.rebugit.registry}}/{{.Values.rebugit.repository}}/tracer:{{ .Values.tracer.image.version }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.tracer.port }}
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  key: environment
                  name: rebugit-global-configmap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: database_user_name
                  name: rebugit-global-configmap
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: database_name
                  name: rebugit-global-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database_user_password
                  name: rebugit-global-secrets
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: database_host
                  name: rebugit-global-configmap
            - name: REBUGIT_AUTH_TYPE
              value: keycloak
            - name: REBUGIT_AUTH_KEYCLOAK_HOST
              valueFrom:
                configMapKeyRef:
                  key: authentication_internal_url
                  name: rebugit-global-configmap
            - name: REBUGIT_AUTH_KEYCLOAK_REALM
              value: rebugit
            - name: REBUGIT_DB_TYPE
              value: postgres