kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "database.network.policy.name" . }}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{ include "database.network.policy.name" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "tracer.deployment.name" . }}
  ingress:
    - ports:
        - port: 8080
          protocol: TCP
