apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tracer.deployment.name" . }}
  labels:
    app: {{ include "tracer.deployment.name" . }}
  annotations:
    {{ include "default.annotations" .}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "tracer.deployment.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "tracer.deployment.name" . }}
    spec:
      containers:
        - name: tracer
          image: "{{.Values.rebugit.registry}}/{{.Values.rebugit.repository}}/tracer:{{ .Values.tracer.image.version }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.tracer.port }}
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  key: environment
                  name: rebugit-global-configmap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: database_user_name
                  name: rebugit-global-configmap
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: database_name
                  name: rebugit-global-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database_user_password
                  name: rebugit-global-secrets
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: database_host
                  name: rebugit-global-configmap
            - name: REBUGIT_AUTH_TYPE
              value: keycloak
            - name: REBUGIT_AUTH_KEYCLOAK_HOST
              valueFrom:
                configMapKeyRef:
                  key: authentication_internal_url
                  name: rebugit-global-configmap
            - name: REBUGIT_AUTH_KEYCLOAK_REALM
              value: rebugit
            - name: REBUGIT_DB_TYPE
              value: postgres