apiVersion: v1
kind: Secret
metadata:
  name: expressjs-todo-secrets
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  rebugit_api_key: {{ .Values.rebugit.apiKey | b64enc }}
  postgres_user: {{.Values.postgresql.postgresqlUsername | b64enc}}
  postgres_password: {{.Values.postgresql.postgresqlPassword | b64enc}}
  mysql_user: {{.Values.mysql.auth.username | b64enc}}
  mysql_password: {{.Values.mysql.auth.password | b64enc}}
  mysql_root_password: {{.Values.mysql.auth.rootPassword | b64enc}}
