apiVersion: v1
kind: Service
metadata:
  name: expressjs-todo-service
  namespace: {{.Release.Namespace}}
  labels:
    app: expressjs-todo-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: {{.Values.todoApi.port}}
      protocol: TCP
  selector:
    app: {{.Values.todoApi.deployment.name}}
