---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kong-care
  region: ap-southeast-1
  version: "1.20"

managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 3
    instanceType: t3.medium
    ssh:
      enableSsm: true