---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rebugit-standalone
  region: us-east-1
  version: "1.20"

managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 3
    instanceType: t3.medium
    ssh:
      enableSsm: true