version: "3.9"
services:
  tracer:
    build:
      context: .
    depends_on:
      - keycloak
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rebugit
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - PGSSLMODE=verify=full
      - GODEBUG=x509ignoreCN=0
      - REBUGIT_AUTH_TYPE=keycloak
      - REBUGIT_AUTH_KEYCLOAK_HOST=http://keycloak:8080
      - REBUGIT_AUTH_KEYCLOAK_REALM=rebugit
      - REBUGIT_DB_TYPE=postgres
    restart: on-failure
    ports:
      - 8080:8080

#  nginx:
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    depends_on:
#      - api
#    ports:
#      - 443:443
#      - 80:80

  dashboard:
    image: rebugit/dashboard
    ports:
      - 3000:8080

  migrator:
    build:
      context: ./db
      dockerfile: migrator.Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rebugit
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres

  postgres:
    image: docker.io/bitnami/postgresql:11
    ports:
      - 5430:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
    volumes:
      - ./db/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
#      - ./db/postgresql-persistence:/bitnami/postgresql

  keycloak:
    image: bitnami/keycloak:13.0.1
    ports:
      - 9000:8080
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_DATABASE_PASSWORD=postgres
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_NAME=keycloak
    depends_on:
      - postgres
