CREATE DATABASE rebugit;

-- Roles and permissions --
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON DATABASE rebugit FROM PUBLIC;

CREATE ROLE readwrite;
GRANT CONNECT ON DATABASE rebugit TO readwrite;
GRANT USAGE, CREATE ON SCHEMA public TO readwrite;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO readwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readwrite;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO readwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO readwrite;

CREATE USER app WITH LOGIN;
ALTER USER app WITH PASSWORD '1830h1u01h389yd'; -- temporary password --
GRANT readwrite TO app;