apiVersion: v2
name: rebugit
description: A Helm chart for Rebugit standalone service
sources:
  - https://github.com/rebugit/rbi-standalone/tree/master/helm
maintainers:
  - name: matteogioioso
    email: gioioso.matteo@gmail.com
type: application
version: 0.1.2
appVersion: 1.16.0
dependencies:
  - name: keycloak
    version: 3.1.1
    repository: file://../authentication/keycloak/helm/keycloak
  - name: postgresql
    version: 10.5.1
    repository: https://charts.bitnami.com/bitnami
