rebugit:
  host: localhost
  tlsEnabled: false

postgresql:
  postgresqlPassword: postgres
  postgresqlUserPassword: p4zzW0rd
  postgresqlMigration:
    registry: public.ecr.aws
    repository: rebugit/migrator
    version: "1.0.4"
    pullPolicy: Always
  extraEnv:
    - name: POSTGRES_DATABASE
      value: rebugit
  image:
    registry: public.ecr.aws
    repository: rebugit/postgres
    tag: "1.0.4"
    pullPolicy: Always

dashboard:
  authenticationMode: keycloak
  podCommonAnnotations: {}
  port: 3000
  image:
    registry: public.ecr.aws
    repository: rebugit/dashboard
    version: "1.0.6"
    pullPolicy: Always
  resources:
    requests: { }
    limits: { }

tracer:
  port: 8080

  # They will be injected in the deployment pod spec
  podCommonAnnotations: {}
  image:
    registry: public.ecr.aws
    repository: rebugit/tracer
    version: "0.1.0"
    pullPolicy: Always
  resources:
    requests: { }
    limits: { }

keycloak:
  image:
    registry: public.ecr.aws
    repository: rebugit/keycloak
    tag: "1.0.4"
    pullPolicy: Always
  auth:
    adminPassword: admin
    adminUser: admin
    createAdminUser: true
    userName: email@example.com
    userPassword: mypassword
  service:
    type: ClusterIP
    port: 8080
  extraEnvVars:
    # This will make sure that keycloak started from a sub-folder will be properly forwarded
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"

  # Those probes come from the Bitnami chart, and they have issues
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
  ingress:
    pathType: Prefix
    path: /rebugit/keycloak
    servicePort: 8080
  postgresql:
    enabled: false