namespace: rebugit

rebugit:
  registry: public.ecr.aws
  repository: g0o0x0q6
  host: localhost
  tlsEnabled: false

postgresql:
  postgresqlPassword: postgres
  postgresqlUserPassword: p4zzW0rd
  postgresqlMigration:
    version: "1625625998"
  extraEnv:
    - name: POSTGRES_DATABASE
      value: rebugit
  image:
    registry: public.ecr.aws
    repository: g0o0x0q6/postgres
    tag: "1625059180"
    pullPolicy: Always

dashboard:
  authenticationMode: keycloak
  port: 3000
  image:
    version: "1624839720"
  resources:
    requests: { }
    limits: { }

tracer:
  port: 8080
  image:
    version: "1625403231"
  resources:
    requests: { }
    limits: { }

keycloak:
  image:
    registry: public.ecr.aws
    repository: g0o0x0q6/keycloak
    tag: "1624772760"
    pullPolicy: Always
  auth:
    adminPassword: admin
    adminUser: admin
    createAdminUser: true
    userName: matteo@hirvitek.com
    userPassword: 123password
  service:
    type: ClusterIP
    port: 8080
  extraEnvVars:
    # This will make sure that keycloak started from a sub-folder will be properly forwarded
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"

    # This will load the initial keycloak config containing the custom realm and client
    - name: KEYCLOAK_EXTRA_ARGS
      value: "-Dkeycloak.import=/config/realm_config.json"
  readinessProbe:
    enabled: false
    httpGet:
      path: /rebugit/keycloak/auth/realms/master
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 30
  livenessProbe:
    enabled: false
    httpGet:
      path: /rebugit/keycloak/auth/realms/master
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 30
  ingress:
    hostname:
    enabled: true
    pathType: Prefix
    path: /rebugit/keycloak
    servicePort: 8080
  externalDatabase:
    port: 5432
    database: keycloak
    host: rebugit-postgresql
    password: postgres
    user: postgres
  postgresql:
    enabled: false
  extraVolumeMounts:
    - name: realm-config
      mountPath: /config
  extraVolumes:
    - name: realm-config
      configMap:
        name: rebugit-keycloak-configmap